### ISSUE TITLE
RecordMarker decision is overflowing SWF 32768 character limit

### ISSUE THREAD

**Issue by ryanwalls** [sclasen/swfsm#165]
My use case...

Run activity A that determines how many permutations of Activity B I need to run.

Decider then schedules X runs of Activity B to run in parallel based on result from Activity A.  

Activity B often fails in a recoverable way, (we are waiting for more compute resources)... so sometimes all X of Activity B fail right away.  If Activity B fails in a recoverable way, I schedule a timer to retry each Activity B at some future point.  

When all Activity B's successfully complete, I then schedule Activity C.  

This workflow has worked great in small cases.  But trying to run 30+ Activity B's at the same time has caused the decider to start doing weird things... Decisions start timing out, everything in the workflow is going slow... I just can't seem to figure out what's going on.  

Have you guys seen deciders or SWF having load problems, when too many activities/timers fail/complete at once?

**Comment by sclasen** [comment]
Hey Ryan, A couple questions

How many events are in the decision task that times out?

Are you making any external calls from the decider?

What is the decision task timeout on this workflow?

The only time we really see decision task timeouts is when something is
broken in our fsm, and we poll down a decision task, attempt to process it
and either panic, or receive a 400 error code due to a bad set of decisions.

In those cases, we go into 'decision churn' where since we don't respond
successfully to the decision task, it times out and gets rescheduled, and
we fail again and again.

If this is what's happening its usually good to go look in the console for
the first timeout in the history and correlate with your log output.

We do have deciders that process ~100 events or so per decision task
without issues fwiw.

**Comment by ryanwalls** [comment]
@sclasen Thanks for pointing me in the right direction.  It wasn't a load or timeout issue.  What is happening is we are hitting the character limit when responding that a decision task is complete.  

So... will have to figure out what we are putting in the decision that is overflowing the character limit.

**Comment by ryanwalls** [comment]
I don't think there is anything right away that the framework would need to change for this issue, so closing.
